version: '3.8'

services:
  web:
    build:
      context: ./source
      dockerfile: Dockerfile.prod
    command: gunicorn kyrgyz_go_db.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/kgf_admin/kyrgyz_go_database/static
    expose:
      - 8000
    env_file:
      - ./source/.env.prod
    depends_on:
      - db

  db:
    image: postgres:14.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./source/.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/kgf_admin/kyrgyz_go_database/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
