version: '3.8'

services:
  web:
    container_name: web
    build:
      context: ./source
    command: gunicorn kyrgyz_go_db.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/kgf_admin/kyrgyz_go_database/static
      - media_volume:/home/kgf_admin/kyrgyz_go_database/uploads
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./source/.env.prod
    depends_on:
      - db
    links:
      - nginx
    networks:
      - my_network

  db:
    container_name: db
    image: postgres:14.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./source/.env.prod.db
    networks:
      - my_network

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/kgf_admin/kyrgyz_go_database/static
      - media_volume:/home/kgf_admin/kyrgyz_go_database/uploads
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - my_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my_network: